### ISSUE TITLE
Adding Authorization Headers

### ISSUE THREAD

**Issue by franzwarning** [seatgeek/SGImageCache#13]
Hi,

I'm currently using SGImageCache in my iOS application and am absolutely loving it. I see you use SGHTTPRequest (a wrapper on AFNetworking) and was wondering if you would consider implementing a way to add authorization headers through SGImageCache. AFNetworking makes it super easy to add these headers:
`[manager.requestSerializer setAuthorizationHeaderFieldWithUsername:@"xxx" password:@"xxx"];`
so I couldn't imagine it would be too difficult.

Thanks!
Raymond

**Comment by staminajim** [comment]
Hi Raymond, you can actually set authorisation headers of an `SGHTTPRequest` (you just give it a dict of the fields that you want to set:
```
    myRequest.requestHeaders = @{ @"user" : @"xxx", @"pass" = @"xxx" }.mutableCopy;
```

So this would be pretty easy to add if we expose a way to set this from `SGImageCache` and pass it on to the `SGHTTPRequest` inside each `SGImageCacheTask`

`+ (void)setHTTPRequestHeaders:(NSDictionary *)dict` on SGImageCache would be nice and easy way to do that.

If you're up for it, feel free to make a pull request and we could merge the feature in...

**Comment by staminajim** [comment]
OK @franzwarning you'll be able to auth your image cache requests using the new additional 
`+ (PMKPromise *)getImageForURL:(NSString *)url requestHeaders:(NSDictionary *)requestHeaders;`
`+ (BOOL)haveImageForURL:(NSString *)url requestHeaders:(NSDictionary *)requestHeaders;`
and
`+ (UIImage *)imageForURL:(NSString *)url requestHeaders:(NSDictionary *)requestHeaders;`
methods in the next SGImageCache release.
