### ISSUE TITLE
Set image for URL

### ISSUE THREAD

**Issue by LarrrrryT** [seatgeek/SGImageCache#17]
Is there a way to set an image with a URL? 

Previously in 2.0.1 I used:
```
[SGImageCache addImageData:data forURL:url];
```

**Comment by sobri909** [comment]
Ah, oops, looks like I broke backwards compat. My bad. I think you should be able to get the same results with this:

```objc
[SGImageCache addData:data forCacheKey:url];
```

If that doesn't work, then this should:

```objc
id cacheKey = [SGImageCache.cache cacheKeyFor:url requestHeaders:nil];
[SGImageCache addData:data forCacheKey:cacheKey];
```

**Comment by nod** [comment]
It would appear that `cache` is not exposed on the interface for `SGCache`.

**Comment by sobri909** [comment]
Hm. Yeah. I wonder why that's an instance method rather than class method. It likely doesn't need to be.

**Comment by staminajim** [comment]
@LarrrrryT New a release is coming soon with an `addImage:forURL:` method.
