### ISSUE TITLE
can't use SGImageCache in Swift

### ISSUE THREAD

**Issue by hashemp206** [seatgeek/SGImageCache#21]
I use this in swift:
```swift
           let promise = SGImageCache.getImageForURL(url)
            promise.then({object in
                if let image = object as? UIImage {
                    self.imageView.image = image
                }
                return nil
            })
```

I get error on then closure: Argument passed to a call that takes no argument

what wrong?

<img width="362" alt="screen shot 2016-06-15 at 8 26 50 pm" src="https://cloud.githubusercontent.com/assets/3206748/16087245/91b4954a-3337-11e6-845c-6131a9ec7579.png">

**Comment by staminajim** [comment]
Hi @hashemp206 You might need to add this code here into a swift file in your project:

https://github.com/mxcl/PromiseKit/issues/165#issuecomment-84942642

Please do let me know if it works!

In the meantime I've opened an issue to port SGImageCache to PromiseKit 2: https://github.com/seatgeek/SGImageCache/issues/22

**Comment by hashemp206** [comment]
thanks it works well. do you know how that extension works? 
you should add this extension to your repository.

**Comment by staminajim** [comment]
Haven't looked too deeply, but looks like swift can't figure out how to get an appropriate obj-c block out of the swift closure, so has to be manually prodded to do so.

I've opened an issue to see if we can bundle the swift extension in a pod subspec and also update the docs - not sure when we'll get around to it though.

Thanks!
