### ISSUE TITLE
SGImageCache is always reading from disk!

### ISSUE THREAD

**Issue by hashemp206** [seatgeek/SGImageCache#24]
I'm using SGImageCache but while I'm scrolling I see there is a little low frame rate on my iPhone 6! I checked in Xcode debug navigator, and noticed disk reading won't rest! means SGImageCache all the time is reading from disk asynchronously! 

``` swift
customImageView.setImageForURL(imageUrl, placeholder:UIImage(named: "food-default"), crossFadeDuration: 0.2)
```
<img width="300" alt="screen shot 2016-07-11 at 11 43 58 am" src="https://cloud.githubusercontent.com/assets/3206748/16722643/4623e11e-475d-11e6-8a80-994460d92a1b.png">

**Comment by staminajim** [comment]
Hi @hashemp206 Can you let me know where in the SGImageCache code the disk access is happening for you?  Can you get the stack trace from the debugger?

Cheers

**Comment by hashemp206** [comment]
disk reading never rest until I stop scrolling!
here is the stack trace:
![stacktrace](https://cloud.githubusercontent.com/assets/3206748/16732925/9ff7f93c-4794-11e6-82d9-7a4b0b324b56.jpg)

**Comment by staminajim** [comment]
Do you mean it's calling `[SGImageCache getImageForURL]` for every pixel scrolled, or once every time a collection view cell comes on screen?

If it's happening for every pixel moved, the call to get the image might be in a bad place.

Are you able to paste the code where you're calling the image fetch from?

**Comment by hashemp206** [comment]
I'm calling the getImageForURL when cell appears on screen (checked). 

```swift
func configureForItem(menuItem: MenuItem, withQuantity quantity: Int) {
if let imageUrl = menuItem.imageUrl {
            SGImageCache.getImageForURL(imageUrl).swiftThen({[unowned self] (object: AnyObject ) -> (PMKPromise?) in
                self.customImageView.image = object as? UIImage
                return nil
            })
        }
}
```

**Comment by staminajim** [comment]
And how big are your images in MB that you're loading in from the cache?

Curious what you're expecting to see here.  Assuming these images are already cached to disk, I expect to see each image loaded in from disk on a background queue once as each collection view cell comes on screen.

**Comment by hashemp206** [comment]
image size averagely about 35 KB on disk. I expected these images cached from disk to memory and not all the time fetched from disk.

**Comment by staminajim** [comment]
Would you be able to give this pattern a try? (sorry for the obj c pseudo-code but should be easily translatable into swift)

```
if ([SGImageCache haveImageForURL:url]) {
    imageView.image = [SGImageCache imageForURL:url];
} else {
    imageView.image = nil;
    [SGImageCache getImageForURL:url].then(^(UIImage *image) {
        if (image) {
            imageView.image = image;
        }
    });
}
```

**Comment by hashemp206** [comment]
nothing changed! still issue exist!

**Comment by staminajim** [comment]
I'm running out of ideas ;)  I don't expect the disk usage on small images to cause stuttering (we even use it with no stuttering on iPhone 4 on reasonably large images).  What does the Xcode profiler say is using up cpu / gpu / causing the framerate stuttering?

**Comment by hashemp206** [comment]
guess what? in ```prepareForReuse``` methods  I was setting imageView.image with placeHolder image on the main thread!

``` swift
self.customImageView.image = UIImage(named: "food-default")
```

**Comment by josegonzalez** [comment]
@hashemp206 Just a quick comment, you may want to use fewer exclamation points when making github comments. It makes it sound like you are yelling at us, when what we're trying to do is help you out. Thanks :)
