### ISSUE TITLE
Type 'SGImageCache' has no member 'getImage'

### ISSUE THREAD

**Issue by bandy101** [seatgeek/SGImageCache#28]
swift4.2  xcode10.1     
SGImageCache.getImage(url: url!.path) { [weak self] image in
                    self?.imageView.image = image   // image loaded async
                }

**Comment by staminajim** [comment]
Hi @bandy101 can you:

* confirm that you're using SGImageCache 3.0.0?

* Are you using cocoa pods to install?

* If installed correctly, this method signature should be in your SGImageCache.h file:
```
+ (void)getImageForURL:(nonnull NSString *)url
             onReceive:(void (^_Nonnull)(UIImage *_Nullable))onReceive
NS_SWIFT_NAME(getImage(url:onReceive:));
```

* Do you need an `import SGImageCache` at the top of your .swift file?

**Comment by bandy101** [comment]
Sorry,my mistake,i change target from ios8.0 to ios9.0,it works well.
thank you

**Comment by bandy101** [comment]
Sorry,my mistake,i change target from ios8.0 to ios9.0,it works well.
thank you
